### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by batuhantoker** [batuhantoker/control_of_quadrupedal_robot#1]
![IMG_5232](https://user-images.githubusercontent.com/55883119/209238746-0f7b8bb5-9cbe-4a9d-a5c8-88436542c834.jpeg)
![IMG_5233](https://user-images.githubusercontent.com/55883119/209238749-aeb857f8-1727-47d0-bb86-5cf9076a7a51.jpeg)
![IMG_5234](https://user-images.githubusercontent.com/55883119/209238750-f2596d51-277d-4549-9aeb-2458714d3ca8.jpeg)

**Comment by tokerbatuhan** [comment]
![static](https://user-images.githubusercontent.com/55883119/209238791-e07cf9d1-a15a-4331-88ef-139996e517ce.png)
![dynamic](https://user-images.githubusercontent.com/55883119/209238792-1334d1e5-23f9-423b-8ca5-bd80a6d9a64a.png)
![static](https://user-images.githubusercontent.com/55883119/209238822-331f9a8b-7a54-4eb9-9a87-021758dfaa94.png)
![dynamic](https://user-images.githubusercontent.com/55883119/209238824-c768da6a-422b-4ba9-9343-c0972a0e3414.png)
![gallopping](https://user-images.githubusercontent.com/55883119/209238825-714b7a35-078f-47f5-83d3-accb3078a3c6.png)
![trot](https://user-images.githubusercontent.com/55883119/209238827-31ebf3d8-c4c4-4e0b-a711-2b0e8097af9f.png)

**Comment by tokerbatuhan** [comment]
![Case1](https://user-images.githubusercontent.com/55883119/209240524-7456a167-62d1-42c3-83c8-837ac186e2a5.png)
![Case3](https://user-images.githubusercontent.com/55883119/209240527-ba81b981-618d-4945-b181-1cdacbff08cb.png)
![Case2](https://user-images.githubusercontent.com/55883119/209240533-1368c72c-4834-4afb-95d7-30bde1f9d189.png)
